### ISSUE TITLE
Rails 4.2.0.beta2 compatibility failed

### ISSUE THREAD

**Issue by zhaohanweng** [DockYard/postgres_ext-serializers#14]
Using the Rails 4.2.0.beta2, and this gem, anything like: Post.where(id: [1,2,3]) will fail.
Everything is fine when using Rails 4.1.6. Maybe this is a rails error.
Here's the error:
```
Loading development environment (Rails 4.2.0.beta2)
>> Post.where(id: [1,2])
(Object doesn't support #inspect)
=>
>> Post.where(id: [1,2]).take
NoMethodError: undefined method `relation' for #<ActiveRecord::ConnectionAdapters::AbstractAdapter::SQLString:0x007fea84b27bb0>
	from /usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/postgres_ext-2.3.0/lib/postgres_ext/arel/visitors/to_sql.rb:7:in `visit_Array'
	from /usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/arel-6.0.0.beta1/lib/arel/visitors/reduce.rb:13:in `visit'
	from /usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/arel-6.0.0.beta1/lib/arel/visitors/to_sql.rb:625:in `visit_Arel_Nodes_In'
	from /usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/arel-6.0.0.beta1/lib/arel/visitors/reduce.rb:13:in `visit'
	from /usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/arel-6.0.0.beta1/lib/arel/visitors/to_sql.rb:783:in `block in inject_join'
	from /usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/arel-6.0.0.beta1/lib/arel/visitors/to_sql.rb:781:in `each'
	from /usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/arel-6.0.0.beta1/lib/arel/visitors/to_sql.rb:781:in `each_with_index'
	from /usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/arel-6.0.0.beta1/lib/arel/visitors/to_sql.rb:781:in `each'
	from /usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/arel-6.0.0.beta1/lib/arel/visitors/to_sql.rb:781:in `inject'
	from /usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/arel-6.0.0.beta1/lib/arel/visitors/to_sql.rb:781:in `inject_join'
	from /usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/arel-6.0.0.beta1/lib/arel/visitors/to_sql.rb:641:in `visit_Arel_Nodes_And'
	from /usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/arel-6.0.0.beta1/lib/arel/visitors/reduce.rb:13:in `visit'
	from /usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/arel-6.0.0.beta1/lib/arel/visitors/to_sql.rb:258:in `block in visit_Arel_Nodes_SelectCore'
	from /usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/arel-6.0.0.beta1/lib/arel/visitors/to_sql.rb:257:in `each'
	from /usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/arel-6.0.0.beta1/lib/arel/visitors/to_sql.rb:257:in `each_with_index'
	from /usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/arel-6.0.0.beta1/lib/arel/visitors/to_sql.rb:257:in `visit_Arel_Nodes_SelectCore'
... 17 levels...
	from /usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.0.beta2/lib/rails/commands/console.rb:9:in `start'
	from /usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.0.beta2/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.0.beta2/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.0.beta2/lib/rails/commands.rb:17:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0.beta2/lib/active_support/dependencies.rb:248:in `require'
	from /usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0.beta2/lib/active_support/dependencies.rb:248:in `block in require'
	from /usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0.beta2/lib/active_support/dependencies.rb:233:in `load_dependency'
	from /usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0.beta2/lib/active_support/dependencies.rb:248:in `require'
	from /Users/zweng/workspace/testapi/bin/rails:8:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0.beta2/lib/active_support/dependencies.rb:242:in `load'
	from /usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0.beta2/lib/active_support/dependencies.rb:242:in `block in load'
	from /usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0.beta2/lib/active_support/dependencies.rb:233:in `load_dependency'
	from /usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0.beta2/lib/active_support/dependencies.rb:242:in `load'
	from /usr/local/var/rbenv/versions/2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/var/rbenv/versions/2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'>>
```

**Comment by shivanibhanwal** [comment]
hi @danmcclain @kenips I am facing same issue, I have migrated my app to rails 4.2  and using AMS 0.8.3 and postgres_ext updated to 2.4.0.beta
As you have mentioned above about arel change. I agree because of that we are getting error 
    #<ArgumentError: wrong number of arguments (1 for 2)>
However I am wondering what is the solution now? As I see @danmcclain has mentioned complete rewrite so does that mean we cannot upgrade to rails 4.2 if we are using postgres_ext_serializer?

**Comment by mcm-ham** [comment]
There's a fix here will create a PR once I get some unit tests for this added: https://github.com/crossroads/postgres_ext-serializers/commit/38d64b2a23d1e1429f6d556fcb75661ba2ef4a79

**Comment by shivanibhanwal** [comment]
@mcm-ham , @danmcclain I still see some issues with it. As I am getting error 

    ActiveRecord::StatementInvalid (PG::ProtocolViolation: ERROR:  
    bind message supplies 0 parameters, but prepared statement "" requires 1

I was looking into the rails discussion for the similar error - https://github.com/rails/rails/issues/15920
Hope that can explain something about it. However at the moment I am unsure whether postgres-ext_serializer is causing issue or rails .

**Comment by mcm-ham** [comment]
I've updated the commit to replace bound values but ideally would like to look for a way to get the framework to pass in sql parameters than manually doing it in string.

**Comment by felixbuenemann** [comment]
Current master supports rails 4.2 as of PR #38.
